mod bool;
mod call;
mod catch;
mod collect_vec;
mod discard;
mod expand_enum;
mod find;
mod get;
mod increment;
mod option;
mod push_into;
mod range;
mod result;
mod split;
pub mod unzip;

pub use self::bool::{AndThen, ThenNone};
pub use call::Call;
pub use catch::Catch;
pub use collect_vec::{CollectVec, CollectVecInto};
pub use discard::{Discard, ToNone};
pub use expand_enum::ExpandEnum;
pub use find::FindFrom;
pub use get::{End, Get2D, GetFirst, GetSlice};
pub use increment::Increment;
pub use option::{CombineOptions, MapNone, NoneOr};
pub use push_into::{ExtendInto, PushInto};
pub use range::RangeTrait;
pub use result::{GetResult, HandleErr, ThenOk};
pub use split::{SplitAround, SplitAroundCopy, SplitCollect};
